from main.format_transformation.mode_choices.mode_choices_enum import ModeChoices, ModeChoicesDesc
from main.format_transformation.mode_choices.diff_params_set_mode import *
from main.format_transformation.mode_choices.diff_struct_same_params_mode import *
from main.format_transformation.mode_choices.same_struct_mode import *
from main.format_transformation.mode_choices.batch_params_mode import *